version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:11
        environment:
          POSTGRES_DB: schedule_arranger
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Dockerize Postgres
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir junit
      - run:
          command: node_modules/.bin/mocha test --reporter mocha-junit-reporter --timeout 10000
          environment:
            MOCHA_FILE: ./junit/test-results.xml
          when: always
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
